### ISSUE TITLE
Generation fails due to missing function in traits.py

### ISSUE THREAD

**Issue by sk33z3r** [sk33z3r/loopymint2#16]
Running generate produces the following error:

```
Traceback (most recent call last):
  File "/loopymint2/generate.py", line 240, in <module>
    main()
  File "/loopymint2/generate.py", line 122, in main
    if total_image > traits.get_variation_cnt():
AttributeError: module 'traits' has no attribute 'get_variation_cnt'
```

It seems there may have been a function saved into `traits.py`, but was not transferred to `traits.example.py`, so the repo did not commit the changes.

**Comment by sk33z3r** [comment]
Confirmed resolved
